# MegaLinter configuration
# Lints only changed files and only selected linters.
VALIDATE_ALL_CODEBASE: false
ENABLE_LINTERS: >
  PHP_PHPCS,
  PHP_PHPLINT,
  JAVASCRIPT_ES,
  CSS_STYLELINT,
  HTML_HTMLHINT

# Restrict web linters to update-api/
JAVASCRIPT_ES_FILTER_REGEX_INCLUDE: "^update-api/"
CSS_STYLELINT_FILTER_REGEX_INCLUDE: "^update-api/"
HTML_HTMLHINT_FILTER_REGEX_INCLUDE: "^update-api/"

# Use project ruleset to target different PHP standards per directory
PHP_PHPCS_CONFIG_FILE: "phpcs.xml"

# Auto-fix behavior controlled from workflow env, can be overridden here if needed
# APPLY_FIXES: all
# APPLY_FIXES_EVENT: pull_request
# APPLY_FIXES_MODE: pull_request
# REPORT_OUTPUT_FOLDER: megalinter-reports
