name: CI Scan

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpstan, phpunit, phpcs

      # Cache Composer (root)
      - name: Cache Composer (root)
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-root-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-root-

      # Cache Composer (update-api)
      - name: Cache Composer (update-api)
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-updateapi-${{ hashFiles('update-api/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-updateapi-

      # Install root dev tools (linters, etc.)
      - name: Composer install (root)
        if: hashFiles('composer.json') != ''
        run: composer install --no-interaction --prefer-dist

      # Install app deps in update-api/
      - name: Composer install (update-api)
        if: hashFiles('update-api/composer.json') != ''
        working-directory: update-api
        run: composer install --no-interaction --prefer-dist

      # PHPCS (uses your root phpcs.xml: WP in mu-plugin/, PSR-12 in update-api/)
      - name: PHPCS
        run: |
          if [ -f vendor/bin/phpcs ]; then vendor/bin/phpcs -q; else phpcs -q; fi

      # PHPStan – root config (covers mu-plugin/ and/or shared rules)
      - name: PHPStan (root)
        if: hashFiles('phpstan.neon') != ''
        run: |
          if [ -f vendor/bin/phpstan ]; then vendor/bin/phpstan analyse --memory-limit=1G; else phpstan analyse --memory-limit=1G; fi

      # PHPStan – update-api override if it has its own config
      - name: PHPStan (update-api)
        if: hashFiles('update-api/phpstan.neon') != ''
        working-directory: update-api
        run: |
          if [ -f vendor/bin/phpstan ]; then vendor/bin/phpstan analyse --memory-limit=1G; else phpstan analyse --memory-limit=1G; fi

      # PHPUnit – prefer update-api tests; fall back to root if present
      - name: PHPUnit (update-api)
        if: hashFiles('update-api/phpunit.xml') != ''
        working-directory: update-api
        run: |
          if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit --coverage-clover ../coverage.xml; else phpunit --coverage-clover ../coverage.xml; fi

      - name: PHPUnit (root)
        if: hashFiles('phpunit.xml') != ''
        run: |
          if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit --coverage-clover coverage.xml; else phpunit --coverage-clover coverage.xml; fi
