name: PR Lint and Auto-Fix

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpcs, php-cs-fixer

      # PHPCBF — only if present; EXCLUDE vendor dirs
      - name: PHPCBF
        run: |
          if [ -f vendor/bin/phpcbf ]; then
            TARGETS=""
            [ -d mu-plugins ] && TARGETS="$TARGETS mu-plugins"
            [ -d update-api ] && TARGETS="$TARGETS update-api"
            if [ -z "$TARGETS" ]; then
              echo "No target dirs for PHPCBF. Skipping."
            else
              php vendor/bin/phpcbf \
                --ignore=vendor,update-api/vendor \
                $TARGETS || true
            fi
          else
            echo "PHPCBF not found in vendor/, skipping."
          fi

      # PHP-CS-Fixer — only if present; feed explicit file list that excludes vendor
      - name: PHP-CS-Fixer
        shell: bash
        run: |
          if [ -f vendor/bin/php-cs-fixer ]; then
            CFG=""
            [ -f .php-cs-fixer.php ] && CFG="--config=.php-cs-fixer.php"

            # Build list of PHP files under mu-plugins/ and update-api/, excluding vendor/
            mapfile -t PHP_FILES < <(git ls-files \
              'mu-plugins/**/*.php' \
              'update-api/**/*.php' \
              ':!:vendor/**' \
              ':!:update-api/vendor/**' || true)

            if [ ${#PHP_FILES[@]} -eq 0 ]; then
              echo "No PHP files to fix (excluding vendor). Skipping."
            else
              # Use xargs to avoid argv length issues
              printf '%s\0' "${PHP_FILES[@]}" | xargs -0 php vendor/bin/php-cs-fixer fix --allow-risky=yes $CFG || true
            fi
          else
            echo "PHP-CS-Fixer not found in vendor/, skipping."
          fi

      # ESLint Fix — only if local binary exists; exclude vendor dirs
      - name: ESLint Fix
        run: |
          if [ -f node_modules/eslint/bin/eslint.js ]; then
            if ls update-api/**/*.js >/dev/null 2>&1; then
              node node_modules/eslint/bin/eslint.js \
                "update-api/**/*.js" \
                --ignore-pattern "vendor/**" \
                --ignore-pattern "update-api/vendor/**" \
                --fix || true
            else
              echo "No JS files under update-api/. Skipping ESLint."
            fi
          else
            echo "Local ESLint not installed (node_modules/eslint/bin/eslint.js missing). Skipping."
          fi

      # Stylelint Fix — only if local binary exists; exclude vendor dirs
      - name: Stylelint Fix
        run: |
          if [ -f node_modules/stylelint/bin/stylelint.mjs ]; then
            if ls update-api/**/*.css >/dev/null 2>&1; then
              node node_modules/stylelint/bin/stylelint.mjs \
                "update-api/**/*.css" \
                --ignore-pattern "vendor/**" \
                --ignore-pattern "update-api/vendor/**" \
                --fix || true
            else
              echo "No CSS files under update-api/. Skipping Stylelint."
            fi
          else
            echo "Local Stylelint not installed (node_modules/stylelint/bin/stylelint.mjs missing). Skipping."
          fi

      # Commit changes directly to the PR branch
      - name: Commit fixes to PR branch
        id: commit_push
        continue-on-error: true
        run: |
          # Ignore chmod-only diffs just in case
          git config core.filemode false

          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: auto-lint fixes"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit."
          fi
