name: PR Lint and Auto-Fix

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpcs, php-cs-fixer

      - uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-root-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-root-

      - uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-updateapi-${{ hashFiles('update-api/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-updateapi-

      - name: Composer install (root)
        if: hashFiles('composer.json') != ''
        run: composer install --no-interaction --prefer-dist || true

      - name: Composer install (update-api)
        if: hashFiles('update-api/composer.json') != ''
        working-directory: update-api
        run: composer install --no-interaction --prefer-dist || true

      # Fix PHP (WordPress in mu-plugins/, PSR-12 in update-api via phpcs.xml)
      - name: PHPCBF
        run: |
          if [ -f vendor/bin/phpcbf ]; then vendor/bin/phpcbf; else phpcbf; fi || true

      - name: PHP-CS-Fixer
        run: |
          if [ -f vendor/bin/php-cs-fixer ]; then vendor/bin/php-cs-fixer fix --allow-risky=yes; else php-cs-fixer fix --allow-risky=yes; fi || true

      # JS/CSS fixes inside update-api/ only (adjust globs if needed)
      - name: ESLint Fix
        run: npx eslint "update-api/**/*.js" --fix || true
      - name: Stylelint Fix
        run: npx stylelint "update-api/**/*.css" --fix || true

      - name: Create PR with fixes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: lint-fixes
          title: "Lint auto-fixes"
          commit-message: "chore: lint auto-fixes"
          body: "Automated fixes across mu-plugins/ and update-api/"
