name: PR Lint and Auto-Fix

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpcs, php-cs-fixer

      # PHPCBF – only if installed in vendor/
      - name: PHPCBF
        run: |
          if [ -f vendor/bin/phpcbf ]; then
            chmod +x vendor/bin/phpcbf
            vendor/bin/phpcbf || true
          else
            echo "PHPCBF not found in vendor/, skipping."
          fi

      # PHP-CS-Fixer – only if installed in vendor/
      - name: PHP-CS-Fixer
        run: |
          if [ -f vendor/bin/php-cs-fixer ]; then
            chmod +x vendor/bin/php-cs-fixer
            vendor/bin/php-cs-fixer fix --allow-risky=yes || true
          else
            echo "PHP-CS-Fixer not found in vendor/, skipping."
          fi

      # ESLint Fix
      - name: ESLint Fix
        run: |
          if [ -d node_modules ] && command -v npx > /dev/null; then
            npx eslint "update-api/**/*.js" --fix || true
          else
            echo "node_modules or npx not found, skipping ESLint."
          fi

      # Stylelint Fix
      - name: Stylelint Fix
        run: |
          if [ -d node_modules ] && command -v npx > /dev/null; then
            npx stylelint "update-api/**/*.css" --fix || true
          else
            echo "node_modules or npx not found, skipping Stylelint."
          fi

      # Commit changes directly to the PR branch
      - name: Commit fixes to PR branch
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: auto-lint fixes"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit."
          fi
