name: Security Scan

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  security-events: write

jobs:
  codeql-js:
    name: CodeQL (JavaScript)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"

  semgrep-php:
    name: Semgrep (PHP)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create dependency file first so caching has a key
      - name: Seed pip cache key
        run: echo "semgrep" > requirements-semgrep.txt

      - name: Set up Python (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'requirements-semgrep.txt'

      - name: Install Semgrep
        run: pip install -r requirements-semgrep.txt

      - name: Run Semgrep (PHP) and output SARIF
        run: |
          semgrep --config=p/php \
                  --include mu-plugins \
                  --include update-api \
                  --exclude vendor \
                  --exclude node_modules \
                  --exclude dist \
                  --sarif --output=semgrep.sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
